### ISSUE TITLE
Lottie scale is not working ok on iPhone X with Xamarin Forms

### ISSUE THREAD

**Issue by marualderete** [Baseflow/LottieXamarin#168]
### Steps to reproduce :scroll:

1. I'm having a project with Xamarin.Forms v3.0.0.482510 and Lottie v2.5.4
2. I use lottie on xaml page as documentation says, I follow this url instructions, very simple steps: https://xamarinhelp.com/lottie-animations-xamarin-forms/

And the animation displays perfect on iphone 6, 6s, 7, even in iphone 8Plus but on Iphone X there is a huge space at the top and at the bottom of the screen that lottie is not covering.
(iOS 11.4)

Please check the images I attached (the red color is a background color I put at lottie xaml control:
![iphone_x](https://user-images.githubusercontent.com/2042329/41186099-d864af66-6b66-11e8-90ca-451a8dbf83d6.PNG)

The code:
```
<forms:AnimationView    
         x:Name="AnimationView" 
         Animation="myFile.json"   
         Loop="False"
         AutoPlay="True" 
         BackgroundColor = Red
         VerticalOptions="FillAndExpand" 
         HorizontalOptions="FillAndExpand" />
```
How can I fix this? 
Kind regards.

**Version:** 2.5.4

**Platform:** 
- [X ] :iphone: iOS
- [X ] :monkey: Xamarin.Forms

**Comment by marualderete** [comment]
@martijn00 
sorry to bother you, but I really need some help with this :/
Kind regards

**Comment by marualderete** [comment]
@martijn00 I was checking the AnimationViewRenderer on this lib, and I made a native class in order to test this issue and maybe this could help you to fix this:
animationView.Bounds = View.Bounds;

**Comment by martijn00** [comment]
@marualderete Can you make a PR to fix this?

**Comment by marualderete** [comment]
@martijn00 Sure, will create a pr soon and let you know :)

**Comment by martijn00** [comment]
@marualderete Any progress on this?

**Comment by vhugogarcia** [comment]
could you share your update @marualderete ? please
