### ISSUE TITLE
When lottie is running and you put the app at background and come back, it freezes.

### ISSUE THREAD

**Issue by marualderete** [Baseflow/LottieXamarin#170]
### Steps to reproduce :scroll:
I have a lottie json file running as splash screen. When the json file **is playing** and I put the app at the background or tapped home button, and then come back to the app, the app get freeze in the middle of the running (json runnin)
**this happens on iOS 11.4.**
and I don't have nothing at "OnResume" method, and nothing strange on the lottie implementation:

`<forms:AnimationView` `x:Name="AnimationView" `
 `                           Animation="{Binding Sample}" `
  `                          Loop="False" `
 `                            AutoPlay="True" `
  `                          VerticalOptions="FillAndExpand" `
   `                         HorizontalOptions="FillAndExpand"/> `

**Version:** 2.5.4

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by LuisDeHaro** [comment]
Same for me, this is somewhat annoying.

**Comment by yevgeny-sotnikov** [comment]
I have such issue, only one way to fix it - call AnimationView.Play when Application.OnResume Called

**Comment by vincentcastagna** [comment]
This is still a bug. When app goes Sleep on Android, lottie animation disappears when you come back. Only when in sleep, if background, no prob. Any news fixing this annoying error ?

**Comment by EmilAlipiev** [comment]
is app freezing for you or lottie animation? On Android, it freezes only lottie animation but not app.

**Comment by OdetteP** [comment]
Did you solve this issue?
