### ISSUE TITLE
PlaybackFinished has no effect on iOS

### ISSUE THREAD

**Issue by less0** [Baseflow/LottieXamarin#176]
### Steps to reproduce :scroll:

1. `AnimationView` in a Xamarin.Forms control

2. Animation is started manually by executing `AnimationView.PlayProgressSegment(0, 1)`

3. `AnimationView.PlaybackFinished()` is called

### Expected behavior :thinking:
Animation should be stopped.

### Actual behavior :bug:
Animation keeps running.

### Configuration :wrench:

**Version:** 2.5.4

**Platform:** 
- [ ✓ ] :iphone: iOS
- [  ] :robot: Android
- [  ] :checkered_flag: WPF
- [  ] :earth_americas: UWP
- [  ] :apple: MacOS
- [  ] :tv: tvOS
- [ ✓ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
@RustamIrzaev can you check this?

**Comment by RustyDaemon** [comment]
@martijn00 I could, but at the moment, I don't have an access to my Windows machine, only to Mac. So I could try to fix the issue only for iOS/Droid platforms, but not for UWP (in case it needs fixing)

**Comment by martijn00** [comment]
@RustamIrzaev Yes iOS/Droid only would be fine, i could make a fix for Windows after you do them.

**Comment by RustyDaemon** [comment]
@martijn00 I've stuck with errors during building the project.
Something like
`/Users/rustamirzaev/Projects/LottieXamarin/Lottie.Forms/Lottie.Forms.csproj: Error NU1202: Package Com.Airbnb.iOS.Lottie 2.5.4 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Com.Airbnb.iOS.Lottie 2.5.4 supports:
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0) (NU1202) (Lottie.Forms)`

Probably, I have to wait until new VS4Mac release will appear. By the way, I will try again after work

**Comment by martijn00** [comment]
Yeah VS4Mac can't compile it, so you have to compile from command line.

msbuild Lottie.sln /t:restore
msbuild Lottie.sln /p:Configuration=Release
